envorior/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('generalapp.generalappurls','generalapp'),namespace='generalapp')),
    path('',include(('publicapp.publicappurls','publicapp'),namespace='publicapp')),
    path('',include(('serventapp.serventappurls','serventapp'),namespace='serventapp')),
    path('',include(('supervisorapp.supervisorappurls','supervisorapp'),namespace='supervisorapp')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

publicapp/models.py
from django.db import models
from generalapp.models import User

# Create your models here.
class Profile(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    contact_no=models.IntegerField()
    full_name=models.CharField(max_length=50)
    dob = models.CharField(max_length=100,blank=True)
    city=models.CharField(max_length=200)
    state=models.CharField(max_length=200)
    pin_code=models.CharField(max_length=100)
    followers=models.ManyToManyField(User,related_name='followers',blank=True)
    followings =models.ManyToManyField(User,related_name='followings',blank=True)
    profile_picture = models.ImageField(upload_to='profilepics',blank=True)

class Post(models.Model):
    pid=models.AutoField(primary_key=True)
    postcaption=models.TextField()
    postimage=models.ImageField(upload_to='posts',blank=True)
    postby=models.ForeignKey(Profile,on_delete=models.CASCADE)
    posteddate=models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User,related_name="likes",blank=True)   

class Job(models.Model):
    j_id = models.BigAutoField(primary_key=True)
    skill_required = models.TextField()
    job_description=models.TextField()
    job_type = models.CharField(max_length=200)
    salary = models.IntegerField()
    job_location = models.CharField(max_length=500)
    job_by = models.ForeignKey(Profile,on_delete=models.CASCADE,blank=True,null=True)
    job_post_date = models.DateField()     

class Notification(models.Model):
    n_msg = models.TextField()
    notification_by = models.CharField(max_length=200) 
    notification_to = models.CharField(max_length=200) 
    notification_date = models.DateField()   

class Donation(models.Model):
    d_id=models.AutoField(primary_key=True)
    donation_type=models.CharField(max_length=200)
    description = models.TextField(blank=True)
    donated_by=models.ForeignKey(Profile,on_delete=models.CASCADE,blank=True,null=True)
    product_image = models.ImageField(upload_to='donate_products',blank=True)
    donar_location = models.CharField(max_length=300)
    rewards = models.ManyToManyField(User,related_name="rewards",blank=True)  

class Complain(models.Model):
    c_id=models.AutoField(primary_key=True)
    complain_type=models.CharField(max_length=200)
    description = models.TextField(blank=True)
    complain_by=models.ForeignKey(Profile,on_delete=models.CASCADE,blank=True,null=True)
    complain_image = models.ImageField(upload_to='complain_images',blank=True)
    complain_location = models.CharField(max_length=300)   
    complain_status = models.CharField(max_length=100,default='unsolved')    

class TopEnvorior(models.Model):
    profile = models.ForeignKey(Profile,on_delete=models.CASCADE)  
    reward = models.IntegerField() 

publicapp/views.py
from django.shortcuts import render,redirect
from generalapp.models import User
from publicapp.models import Profile,Post,Job,Notification,Donation,Complain,TopEnvorior
from datetime import date
from django.utils import timezone
from django.views.decorators.cache import cache_control #validate thourgh server instead of browser
from django.http import JsonResponse
from serventapp.models import Event


# Create your views here.
@cache_control(no_cache=True ,must_revalidate=True,no_store=True)
def publichome(request):
    try:
        if request.session['email']!=None:
            #common code for user details
            current_user = request.session['email']
            current_user_details = Profile.objects.get(user=current_user)
            top = TopEnvorior.objects.get(profile=current_user_details)
            total_reward = top.reward
            #top three envorior
            top_envorior = TopEnvorior.objects.order_by('-reward')[:8]

            #code for publichome
            post = Post.objects.all().order_by('-posteddate')
            return render(request,'publichome.html',locals())
        
    except KeyError:
        return redirect('generalapp:login')    
      
@cache_control(no_cache=True ,must_revalidate=True,no_store=True)
def uploadpost(request):
    try:
        if request.session['email']!=None:
            #common code for user details
            current_user = request.session['email']
            current_user_details = Profile.objects.get(user=current_user)
            top = TopEnvorior.objects.get(profile=current_user_details)
            total_reward = top.reward
            #top three envorior
            top_four_envorior = TopEnvorior.objects.order_by('-reward')[:4]

            #code for uploadpost
            if request.method=='POST':
                caption = request.POST['caption']
                p_image = request.FILES['pimg']
                Post.objects.create(postcaption=caption,postimage=p_image,
                                    postby=current_user_details)
                return redirect('publicapp:publichome')
    except KeyError:
        return redirect('generalapp:login')
    

def like_post(request,id):
    current_user = request.session['email']
    current_user_details = Profile.objects.get(user=current_user)
    user_instance = User.objects.get(email=current_user)
    post = Post.objects.filter(pid=id)
    if user_instance in post[0].likes.all():
        post[0].likes.remove(user_instance)
    else:
        post[0].likes.add(user_instance)

    #getting all rewards on donation
    current_user_donation = Donation.objects.filter(donated_by__full_name=current_user_details.full_name)
    total_reward_on_donation = 0
    for i in current_user_donation:
        a = i.rewards.count()
        total_reward_on_donation = total_reward_on_donation + a  
    #getting total reward onpost
    current_user_post = Post.objects.filter(postby__full_name=current_user_details.full_name)
    total_reward_on_post = 0
    for i in current_user_post:
        a = i.likes.count()
        total_reward_on_post = total_reward_on_post + a    
    #update total reward
    top = TopEnvorior.objects.get(profile=current_user_details)
    top.reward=total_reward_on_post+total_reward_on_donation
    top.save()

    return redirect("publicapp:publichome")

def jobs(request):
    #common code for user details
    current_user = request.session['email']
    current_user_details = Profile.objects.get(user=current_user)
    top = TopEnvorior.objects.get(profile=current_user_details)
    total_reward = top.reward
    #code for job  
    jobs = Job.objects.all() 
    #top  envorior
    top_envorior = TopEnvorior.objects.order_by('-reward')[:8]   
    return render(request,'jobs.html',locals())

def uploadjob(request):
    #common code for user details
    current_user = request.session['email']
    current_user_details = Profile.objects.get(user=current_user)
    top = TopEnvorior.objects.get(profile=current_user_details)
    total_reward = top.reward
    #top  envorior
    top_envorior = TopEnvorior.objects.order_by('-reward')[:8] 

    #code for upload job   
    if request.method=='POST':
        skill_required = request.POST['skill']
        job_description = request.POST['description']
        job_type = request.POST['job_type']
        salary = request.POST['salary']
        job_location = request.POST['location']
        new_job=Job(skill_required=skill_required,
                    job_description=job_description,
                    job_type=job_type,salary=salary,
                    job_location=job_location,
                    job_by = current_user_details,
                    job_post_date=date.today())
        new_job.save()
        return redirect("publicapp:jobs")

# def jobform(request):
#     #common code for user details
#     current_user = request.session['email']
#     current_user_details = Profile.objects.get(user=current_user)
#     top = TopEnvorior.objects.get(profile=current_user_details)
#     total_reward = top.reward
#     #top  envorior
#     top_envorior = TopEnvorior.objects.order_by('-reward')[:8] 
#     return render(request,'jobs.html',locals())

def apply_job(request,id):
    #common code for user details
    current_user = request.session['email']
    current_user_details = Profile.objects.get(user=current_user)
    top = TopEnvorior.objects.get(profile=current_user_details)
    total_reward = top.reward
    #top  envorior
    top_envorior = TopEnvorior.objects.order_by('-reward')[:8] 

    #apply job code   
    #getting details of job by 
    job = Job.objects.get(j_id=id)
    job_by_name  = job.job_by.full_name
    job_by_profile = Profile.objects.get(full_name=job_by_name)
    job_by_email = job_by_profile.user.email

    #getting the details of user who apply for job
    applicant = Profile.objects.get(user__email=current_user)
    applicant_name=applicant.full_name
    applicant_contact = applicant.contact_no
    msg = " Hii,{} apply for a job that you posted for {}. The details of applicant are as follows- Name = {} , contact_no = {}".format(applicant_name,job.job_type,applicant_name,applicant_contact)
    notification = Notification(n_msg=msg,notification_by=current_user,notification_to=job_by_email,notification_date=date.today())
    notification.save()
    return redirect("publicapp:jobs")

def notifications(request):
    #common code for user details
    current_user = request.session['email']
    current_user_details = Profile.objects.get(user=current_user)
    top = TopEnvorior.objects.get(profile=current_user_details)
    total_reward = top.reward
    #top three envorior
    top_envorior = TopEnvorior.objects.order_by('-reward')[:8]

    #notification code   
    notifications = Notification.objects.filter(notification_to=current_user)
    return render(request,'notifications.html',locals())

def donation(request):
    #common code for user details
    current_user = request.session['email']
    current_user_details = Profile.objects.get(user=current_user)
    top = TopEnvorior.objects.get(profile=current_user_details)
    total_reward = top.reward
    #top  envorior
    top_envorior = TopEnvorior.objects.order_by('-reward')[:8] 
    #donation code  
    donation = Donation.objects.all() 
    return render(request,'donate.html',locals())

def postdonation(request):
    #common code for user details
    current_user = request.session['email']
    current_user_details = Profile.objects.get(user=current_user)
    top = TopEnvorior.objects.get(profile=current_user_details)
    total_reward = top.reward
    #top  envorior
    top_envorior = TopEnvorior.objects.order_by('-reward')[:8] 
    #post donation code   
    if request.method=='POST':
        donation_type=request.POST['donation_type']
        description=request.POST['description']
        product_image=request.FILES['p_image']
        donar_location=request.POST['location']
        donate = Donation(donation_type=donation_type,description=description,
                          product_image=product_image,
                          donar_location=donar_location,donated_by=current_user_details)
        donate.save()
        #get all donation  
        donation = Donation.objects.all() 
    return render(request,'donate.html',locals())

def reward_donate(request,id):
    current_user = request.session['email']
    current_user_details = Profile.objects.get(user=current_user)
    user_instance = User.objects.get(email=current_user)

    donate = Donation.objects.filter(d_id=id)
    if user_instance in donate[0].rewards.all():
        donate[0].rewards.remove(user_instance)
    else:
        donate[0].rewards.add(user_instance)

    #getting all rewards on donation
    current_user_donation = Donation.objects.filter(donated_by__full_name=current_user_details.full_name)
    total_reward_on_donation = 0
    for i in current_user_donation:
        a = i.rewards.count()
        total_reward_on_donation = total_reward_on_donation + a  
    #getting total reward onpost
    current_user_post = Post.objects.filter(postby__full_name=current_user_details.full_name)
    total_reward_on_post = 0
    for i in current_user_post:
        a = i.likes.count()
        total_reward_on_post = total_reward_on_post + a    
    #update total reward
    top = TopEnvorior.objects.get(profile=current_user_details)
    top.reward=total_reward_on_post+total_reward_on_donation
    top.save()

    #common code for user details
    current_user = request.session['email']
    current_user_details = Profile.objects.get(user=current_user)
    top = TopEnvorior.objects.get(profile=current_user_details)
    total_reward = top.reward
    #top  envorior
    top_envorior = TopEnvorior.objects.order_by('-reward')[:8] 
    #donation code  
    donation = Donation.objects.all() 

    return render(request,'donate.html',locals())

def get_donation(request,id):
    #common code for user details
    current_user = request.session['email']

publicapp/templates/about.html
{% extends 'publicparent.html' %}
{% load static %}

{% block title %} About {% endblock title %}

{%block content%}


  <div class="info-layout" style="border-style: dashed; border-color:white;">
   <div class="txt-1 info-layout-header" style="display: flex;"><h3>About</h3>
      <div class="logo ">
         <!-- navbar logo -->
         <!-- <img class="logo-img" src="{% static 'img/logoimage.png' %}" alt=""> -->
         
          </div>
          <div class="logo-txt">
             <!-- <p style="font-family: cursive; color: green; font-size:1.6rem;">ENVORIOR</p> -->
             <!-- <p>Environment Worior</p> -->
              </div></div>
              
              <p class="txt-2" style="margin-top:10px;">
               Social Warrior is the ultimate social media platform for environmental advocates and NGOs 
               committed to preserving our planet. Here, NGOs can easily list their organizations, 
               share their crucial initiatives, post job opportunities, and initiate fundraising campaigns.
                Our platform thrives on collaboration and provides a space where individuals passionate about 
                environmental causes can connect, share ideas, and join forces to address pressing environmental issues. 
                Join us in our mission to protect and nurture nature for a sustainable and thriving world
              </p></br>
            <div class="info-layout-footer"><span class="txt-2"><i class="fa-solid fa-envelope"></i></span>
              <span class="txt-2">info@SocialWarrior.com</span></div></br>
              <span class="txt-2"><i class="fa-solid fa-phone"></i></span>
              <span class="txt-2">00999001111</span></div>
  </div>
 
          

  


{% endblock %}

publicapp/templates/complain.html
{% extends 'publicparent.html' %} {% load static %} {% block title %} Dashboard
{% endblock title %} {%block content%}
<div id="form-layout" style="background-color: #ffffff; border-radius: 5px;">
  <p class="txt-1 pt-4"></p>
  <div class ="img">
    <img src="{% static 'img/complain.png' %}" height="100%" width="100%" />
  </div>
 

 
<form action="#" method='POST' enctype="multipart/form-data">
  {% csrf_token %}
 
  <select class="form-select" style="border: 1px solid #e2e6e9 !important; " name="complain_type" id=""  >
      <option selected disabled>Select Complain Type</option>
      <option value="Water Problem">Water</option>
      <option value="Cleaning">Cleaning</option>
      <option value="Garbage">Garbage</option>
      <option value="Improper Garbage Disposal">Improper Garbage Disposal</option>
      <option value="Damage Bins">Damage Bins</option>
      <option value="Illegal Dumping">Illegal Dumping</option>
      <option value="Water Leakages">Water Leakages</option>
      <option value="Poor Sanitation">Poor Sanitation</option>
      <option value="Other">Other</option>
  </select>
  <input id="uploadInput" class="form-control w-100 mt-3" type="file" name="complain_image" accept=".png,.jpg" placeholder=" Upload Media (Image) ">
  <div class="row mt-3">
       
    <div class="" style="display: flex; justify-content: center;"><img id="imagePreview" src="#"></div>
 </div>
  <textarea class="form-control mt-3" type="text" name="description" rows="3" placeholder="Your Message"></textarea>
  <input style="border: 1px solid #e2e6e9 !important; " class="form-control mt-3" type="text" name="location" placeholder="Location">
  <button type="submit" class="btn btn-primary mt-3 w-100">complain</button>
</form>
</div>
{% endblock %}

publicapp/templates/contact.html
{% extends 'publicparent.html' %}
{% load static %}

{% block title %} Dashboard {% endblock title %}

{%block content%}

<div id="form-layout" style="border-style: dashed; border-color:white;">
   <p class="txt-1">Contact Us</p> 
   <div class ="img">
       <img src="{% static 'img/contact.png' %}" height="100%" width="100%">
      </div>

<form >
   <div class="search"><input type="text" placeholder=" Search "></div>
   <div class="search"><input type="text" placeholder=" Upload Media (Image/Video) "></div>
   <div class="txt-box"><textarea type="text" rows="8" placeholder=" Message "></textarea></div>
   
   
  <button type="submit" class="btn btn-primary">Contact</button>
   
</form>
 
</div>

{% endblock %}

publicapp/templates/followers.html
{% extends 'publicparent.html' %}
{% load static %}

{% block title %} Followers {% endblock title %}

{% block content %}
<div class="follower">
  <p class="txt-3" style="margin-left: 3rem;"><i>400+ peoples are followings you</i></p>
  {% for i in followers_details %}
<div class="user-profile">
  {% if pic %}
   <a href="">
    <img class="profile-img" src="{{i.pic.url}}" alt=""/>
   </a>
  {% else %}
    <a href="">
      <img class="profile-img" src="{% static 'img/user.jpeg' %}" alt=""/>
    </a>
  {% endif %}  
    <div class="profile-txt" style="position: relative; padding-bottom: 0.5rem;">
      <p class="txt-2">{{i.full_name}}</p>
      <p class="txt-3">No.of Followings :  {{i.followings}}</p>
      <span class=" " style="float: right; position: absolute;top: 0.3rem;right: 1rem; padding: 0.3rem 1rem;">Follow</span>
    </div>

    
</div>

{% endfor %}
</div>

{% endblock %}

publicapp/templates/followings.html
{% extends 'publicparent.html' %}
{% load static %}

{% block title %} Followings {% endblock title %}

{% block content %}

<div class="follower">
  <p class="txt-3 mt-2" style="margin-left: 3rem;"><i class="mt-3 mb-3">You are followings {{current_user_followings.count}} people</i></p>
  {% for i in following_details %}
<div class="user-profile">
   {% if pic %}
   <a href="">
    <img class="profile-img" src="{{i.pic.url}}" alt=""/>
   </a>
  {% else %}
    <a href="">
      <img class="profile-img" src="{% static 'img/user.jpeg' %}" alt=""/>
    </a>
  {% endif %}  
    <div class="profile-txt" style="position: relative; padding-bottom: 0.5rem;">
      <p class="txt-2">{{i.full_name}}</p>
      <p class="txt-3">No.of Followers:{{i.followers}}</p>
      <span class="btn btn-primary" style="float: right; position: absolute;top: 0.3rem;right: 1rem; padding: 0.3rem 1rem;">Following</span>
    </div>

    
</div>

{% endfor %}
</div>
{% endblock %}

publicapp/templates/notifications.html
{% extends 'publicparent.html' %}
{% load static %}

{% block title %} Notifications {% endblock title %}

{% block content %}
<h3 class="mt-3 mb-2"><b>Notifications</b></h3>
{% for i in notifications %}

<ol class="list-group list-group-numbered mt-2">
  <li class="list-group-item d-flex justify-content-between align-items-start">
    <div class="ms-2 me-auto">
      <div class="fw-bold">Message by : {{i.notification_by}}</div>
      <div class="fw-bold">Message :</div>
      {{i.n_msg}}
    </div>
    <span class="badge text-bg-primary rounded-pill">1</span>
  </li>
</ol>
{% endfor %}
{% endblock %}

publicapp/templates/profile.html
{% extends 'publicparent.html' %} {% load static %} 
{% block title %} Profile{% endblock title %} 
{%block content%}
<div class="profile" style="background: #ffffff;">
  
  <div class="upper">
    <div class="items">

      <div class="user-profile"  style="position: relative;">
        {% if current_user_details.profile_picture %}
          <a><img class="profile-img" src="{{ current_user_details.profile_picture.url }}" alt=""></a>   
        {% else %}
          <a><img class="profile-img" src="{% static 'img/profile.png' %}" alt=""></a>
        {% endif %}
    
        <span  class="plus-icon" data-bs-toggle="modal" data-bs-target="#profileModal">+</span>
      </div> 
      <p class="txt-2">{{current_user_details.full_name}}</p>
      </div>
      <div class="items">
        <p class="txt-2">{{post.count}}</p>
        <p class="txt-2">No of post</p>
      </div>
      <div class="items">
        <p class="txt-2">{{current_user_details.followers.count}}</p>
        <a href="{%url 'publicapp:followers'%}"><p class="txt-2">Follower</p></a>
      </div>
      <div class="items">
        <p class="txt-2">{{current_user_details.followings.count}}</p>
        <a href="{%url 'publicapp:followings'%}"><p class="txt-2">Following</p></a>
       
      </div>
    </div>
    <div class="row">
  
    </div>
    <div class="lower">
      <div class="items">
        <!-- <button class="btn btn-secondary profile-post-btn">Post</button> -->
        <span class="txt-2"><i class="fa-solid fa-th profile-all-btn"></i></span>
      </div>
      <div class="items">
        <!-- <button class="btn btn-secondary profile-post-btn">Post</button> -->
        <span class="txt-2"><i class="fa-solid fa-file-alt profile-post-btn"></i></span>
      </div>
      <div class="items">
        <!-- <button class="btn btn-secondary profile-complain-btn">complain</button> -->
        <span class="txt-2"><i class="fa-solid fa-comments profile-complain-btn"></i></span>
      </div>
      <div class="items">
        <!-- <button class="btn btn-secondary profile-job-btn">Job</button> -->
        <span class="txt-2"><i class="fa-solid fa-briefcase profile-job-btn"></i></span>
      </div>
      <div class="items">
        <!-- <button class="btn btn-secondary profile-donation-btn">Donation</button> -->
        <span class="txt-2"><i class="fa-solid fa-hand-holding-dollar profile-donation-btn"></i></span>
      </div>
    </div>
  </div>
  <!--  profile data -->
  <div class="profile-data">
    
<!-- #showing user complain -->
{% for c in complain %}
<div class="feed-post profile-complain">
  <div class="feed-header">
     <!-- <div class="user-profile">
        {% if c.complain_by.profile_picture %} 
             <a href=""><img class="profile-img" src="{{ c.complain_by.profile_picture.url }}" alt=""/> </a>
        {% else %}
             <a href=""><img class="profile-img" src="" alt=""/> </a>
        {% endif %} 
    </div> -->
        <div class="profile-txt">
         <a href="" class="txt-2"><p><b>Complaints type : </b>{{c.complain_type}}</p></a>
         <!-- <a href="" class="txt-3"><p>complaints by : {{c.complain_by.full_name}}</p></a> -->
         
        </div>     
            </div>
  <div class="feed-content">
     <p class="txt-3"><b>Description: </b>{{c.description}}</p>
     <p class="txt-3"><b>Location: </b>{{c.complain_location}}</p>
          <div style="object-fit: cover;">
              {% if c.complain_image %} 
                 <a href=""><img src="{{ c.complain_image.url }}" alt="" height="150px" width="100%"/> </a>
              {% else %}
                 <a href=""><img  src="{% static 'img/profile.png' %}" alt="" height="150px" width="100%"/> </a>
              {% endif %}
          </div>
          
  </div>

  <div class="feed-footer ">
    
     <a href="" class="text-decoration-none w-100 mx-2">
      {% if c.complain_status == 'solved' %}
        <span class="txt-1" style="background-color: rgb(58, 214, 19);" >Solved</span>
      {% else %} 
        <span class="txt-1" style="background-color: red;" >Unsolved</span> 
      {% endif %}
    </a>
    <div class="">
     <a href="/deletecomplain/{{c.c_id}}" class="text-decoration-none bg-danger">
      
       <span class="txt-1 mx-2">Delete</span>
   </a>
 </div>
  </div>
 
</div>
{% endfor %}
    
   <!-- #showing user donation -->
   {% for d in donation %}
   <div class="feed-post profile-donation">
      <div class="feed-header" style="padding-right: 1rem;">
         <!-- <div class="user-profile">
            {% if d.donated_by.profile_picture %}
               <a><img class="profile-img" src="{{d.donated_by.profile_picture.url}}" alt=""></a>
            {% else %}
               <a><img class="profile-img" src="" alt=""></a>
            {% endif %}   
            <div class="profile-txt">
            <a href="" class="txt-2"><p>{{d.donated_by.full_name}}</p></a> -->
            <!-- <a href="" class="txt-3"><p></p></a>
         </div>    
         </div>   -->
         <p class="w-100 text-light"><b>Donation Type</b></p>
         <p class="text-light">{{d.donation_type}}</p>
      </div>
      <div class="feed-content">
         
         
            
         <p class="txt-2">Description</p>
         <p class="txt-3">{{d.description}}</p>
            
         <p class="txt-2">Donar locations</p>
         <p class="txt-3">{{d.donar_location}}</p>

         <div style="height: 10rem; object-fit: cover;">
            {% if d.product_image %}
              <img src="{{d.product_image.url}}" height="150px" width="100%">
            {% endif %}  
         </div>
      </div>

      
      <div class="feed-footer">
         <a href="/deletedonation/{{d.d_id}}" class="text-decoration-none">
          
           <span class="txt-1">Delete Donation</span>
       </a>
     </div>
   </div>
{% endfor %}
    <!-- this is post data -->
  {% for post in post %}
  <div class="feed-post profile-post">
     <div class="feed-header">
        <div class="user-profile">
         
                 
           <div class="profile-txt">
            <!-- <a href="" class="txt-2"><p>{{post.postby.full_name}}</p></a> -->
            <a href="" class="txt-3"><p>{{post.posteddate}}</p></a>
            
         </div>     
               </div>
     </div>
     <div class="feed-content">
        <p class="txt-3">{{post.postcaption}}</p>
             <div style="height: 10rem; object-fit: cover;">
              <img src="{{post.postimage.url}}" height="100%" width="100%">
             </div>
             
     </div>
     <div class="feed-footer">
         <a href="/deletepost/{{post.pid}}" class="text-decoration-none">
          
           <span class="txt-1">Delete Post</span>
       </a>
     </div>
  </div>
  {% endfor %}
  <!-- this is job data -->
  {% for job in jobs %}
  <div class="feed-post profile-job">
     <div class="feed-header" style="padding-right: 1rem;">
        <div class="user-profile">
           {% if job.job_by.profile_picture %}
             <a><img class="profile-img" src="{{ job.job_by.profile_picture.url }}" alt=""></a>
           {% else %}
             <a><img class="profile-img" src="" alt=""></a>
           {% endif %}  
           <div class="profile-txt">
            <!-- <a href="" class="txt-2"><p>{{job.job_by.full_name}}</p></a> -->
            <a href="" class="txt-3"><p>{{job.job_post_date}}</p></a>
         </div>    
         </div>  
     </div>
     <div class="feed-content">
        <p class="txt-2">Job Type:{{job.job_type}}</p>   
        <p class="txt-2">Required Skills:{{job.skill_required}}</p>  
        <p class="txt-2">Salary:{{job.salary}}</p>  
        <p class="txt-2">Job Description:{{job.job_description}}</p> 
        <p class="txt-2">Job Location:{{job.job_location}}</p>     
     </div>
        <div class="feed-footer">
           <a href="/deletejob/{{job.j_id}}">
              <button type="submit" class="btn btn-primary">Delete Job</button>
          </a>
        </div>
  </div>
  {% endfor %}
</div>
 
</div>


 <!-- profile pop-up -->
 <div class="modal fade" id="profileModal" tabindex="-1" aria-labelledby="profileModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-fullscreen-sm-down">
     <div class="modal-content">
        <div class="modal-header">
           <h1 class="modal-title fs-5" id="profileModalLabel">Create profile</h1>
           <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-data">
           <!-- form for add profile -->
           <form action="{% url 'publicapp:changeuserprofile' %}" method='POST' enctype="multipart/form-data">
              {% csrf_token %}
              <div class="container" >
              
                 <div class="row mt-3">
                    <div class=""><input id="uploadInput" class="form-control w-100" type="file" name="pic" accept=".png,.jpg" placeholder=" Upload Media (Image) "></div>

                 </div>
                 <div class="row mt-3">
       
                    <div class="" style="display: flex; justify-content: center; 
                    border-radius: var(--border-radius2);
                    height: 10rem;
                    width: 10rem;"><img id="imagePreview" src="#"></div>
                 </div>
                 <div class="row" style="width: 100%;margin-left: 0rem;">
                    <button type="submit" class="mt-3 mb-3 btn btn-primary profilebutton">Change Pic</button>
                 </div>
              </div>
          </form>
        </div>
     </div>
  </div>
</div>

{% endblock %}